services:
  minio:
    extends:
      file: ./minio/compose.yaml
      service: minio
  mongodb:
    extends:
      file: ./mongodb/compose.yaml
      service: mongodb
  mysql:
    extends:
      file: ./mysql/compose.yaml
      service: mysql
  phpmyadmin:
    extends:
      file: ./mysql/compose.yaml
      service: phpmyadmin
  postgresql:
    extends:
      file: ./postgresql/compose.yaml
      service: postgresql
    ports:
      - 5432:5432
    volumes:
      - "./postgresql/data:/var/lib/postgresql"
    command: >
      postgres
        -c wal_level=logical
        -c max-replication_slots=5
        -c max_wal_senders=5
  postgresql-read:
    extends:
      file: ./postgresql/compose.yaml
      service: postgresql
    container_name: postgresql-read
    ports:
      - 5433:5432
    volumes:
      - "./postgresql/data-replica:/var/lib/postgresql"
  pgadmin:
    extends:
      file: ./postgresql/compose.yaml
      service: pgadmin
  redis:
    extends:
      file: ./redis/compose.yaml
      service: redis
