x-common: &common
  restart: unless-stopped
  networks:
    - project-container-net

x-common-env: &common-env
  TZ: ${TZ:-UTC}

x-common-healthcheck: &common-healthcheck
  interval: 1m
  timeout: 5s
  retries: 5
  start_period: 10s

x-postgress-env: &postgress-env
  POSTGRES_USER: ${POSTGRES_USER:-admin}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin}
  POSTGRES_DB: ${POSTGRES_DB:-admin}

x-postgres: &postgres
  image: postgres:alpine
  environment:
    <<: [ *common-env, *postgress-env ]
  healthcheck:
    <<: *common-healthcheck
    test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]

services:
  redis:
    <<: *common
    image: redis:alpine
    ports:
      - 6379:6379
    environment:
      <<: *common-env
    healthcheck:
      <<: *common-healthcheck
      test: [ "CMD", "redis-cli", "ping" ]

  minio:
    <<: *common
    image: minio/minio
    command: server /data --console-address ":9001"
    ports:
      - 9000:9000 # S3 API
      - 9001:9001 # Web console
    environment:
      <<: *common-env
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-admin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-admin}
    volumes:
      - ./volumes/minio-data:/data

  mongodb:
    <<: *common
    image: mongo
    ports:
      - 27017:27017
    environment:
      <<: *common-env
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-admin}
    volumes:
      - ./volumes/mongodb-data:/data/db
    healthcheck:
      <<: *common-healthcheck
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]

  mysql:
    <<: *common
    image: mysql
    ports:
      - "3306:3306"
    environment:
      <<: *common-env
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-admin}
      MYSQL_USER: ${MYSQL_USER:-admin}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-admin}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-${MYSQL_USER:-test}}
    volumes:
      - ./volumes/mysql-data:/var/lib/mysql
    healthcheck:
      <<: *common-healthcheck
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost -u root -p$$MYSQL_ROOT_PASSWORD || exit 1" ]

  phpmyadmin:
    <<: *common
    image: phpmyadmin
    ports:
      - 81:80
    environment:
      <<: *common-env
      PMA_ARBITRARY: 1
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: ${MYSQL_USER:-admin}
      PMA_PASSWORD: ${MYSQL_PASSWORD:-admin}

  postgresql:
    <<: [ *common, *postgres ]
    command: >
      postgres
        -c wal_level=logical
        -c max-replication_slots=10
        -c max_wal_senders=10
    ports:
      - 5432:5432
    volumes:
      - ./volumes/postgresql-data:/var/lib/postgresql

  postgresql-replica:
    <<: [ *common, *postgres ]
    ports:
      - 5433:5432
    volumes:
      - ./volumes/postgresql-replica-data:/var/lib/postgresql

  pgadmin:
    <<: *common
    image: dpage/pgadmin4
    ports:
      - 82:80
    environment:
      <<: *common-env
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@example.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
      - ./volumes/pgadmin-data:/var/lib/pgadmin

  opensearch:
    <<: *common
    image: opensearchproject/opensearch
    environment:
      <<: *common-env
      discovery.type: single-node
      bootstrap.memory_lock: true # Disable JVM heap memory swapping
      OPENSEARCH_JAVA_OPTS: "-Xms512m -Xmx512m" # Set min and max JVM heap sizes to at least 50% of system RAM
      OPENSEARCH_INITIAL_ADMIN_PASSWORD: ${OPENSEARCH_INITIAL_ADMIN_PASSWORD} # Sets the demo admin user password when using demo configuration, required for OpenSearch 2.12 and later
    ulimits:
      memlock:
        soft: -1 # Set memlock to unlimited (no soft or hard limit)
        hard: -1
      nofile:
        soft: 65536 # Maximum number of open files for the opensearch user - set to at least 65536
        hard: 65536
    volumes:
      - ./volumes/opensearch-data:/usr/share/opensearch/data # Creates volume called opensearch-data1 and mounts it to the container
    ports:
      - 9200:9200 # REST API
      - 9600:9600 # Performance Analyzer

  opensearch-dashboards:
    <<: *common
    image: opensearchproject/opensearch-dashboards
    ports:
      - 5601:5601
    environment:
      <<: *common-env
      OPENSEARCH_HOSTS: '["https://opensearch:9200"]' # Define the OpenSearch nodes that OpenSearch Dashboards will query

networks:
  project-container-net:
