services:
  # mongodb:
  #   image: mongodb/mongodb-community-server
  #   container_name: mongodb
  #   ports:
  #     - 27017:27017
  #   volumes:
  #     - ./data:/data/db
  #   environment:
  #     TZ: ${TZ:-UTC}
  #     MONGODB_INITDB_ROOT_USERNAME: ${MONGODB_INITDB_ROOT_USERNAME:-admin}
  #     MONGODB_INITDB_ROOT_PASSWORD: ${MONGODB_INITDB_ROOT_PASSWORD:-admin}
  #   restart: unless-stopped
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
    environment:
      TZ: ${TZ:-UTC}
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_INITDB_ROOT_USERNAME:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_INITDB_ROOT_PASSWORD:-admin}
    restart: unless-stopped
  # mongo-express:
  #   image: mongo-express
  #   container_name: mongo-express
  #   restart: unless-stopped
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_BASICAUTH_USERNAME: ${MONGODB_INITDB_ROOT_USERNAME:-admin}
  #     ME_CONFIG_BASICAUTH_PASSWORD: ${MONGODB_INITDB_ROOT_PASSWORD:-admin}
  #     ME_CONFIG_MONGODB_URL: mongodb://${MONGODB_INITDB_ROOT_USERNAME:-admin}:${MONGODB_INITDB_ROOT_PASSWORD:-admin}@mongodb:27017/
