services:
  mysql:
    image: mysql
    container_name: mysql
    environment:
      TZ: ${TZ:-UTC}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-admin}
      MYSQL_USER: ${MYSQL_USER:-admin}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-admin}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-${MYSQL_USER:-test}}
    ports:
      - "3306:3306"
    volumes:
      - "./data:/var/lib/mysql"
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    environment:
      TZ: ${TZ:-UTC}
      PMA_ARBITRARY: 1
      # PMA_HOST: mysql
      # PMA_PORT: 3306
      # PMA_USER: ${MYSQL_USER:-admin}
      # PMA_PASSWORD: ${MYSQL_PASSWORD:-admin}
    restart: unless-stopped
    ports:
      - 81:80
